model_config:
  d_model: 256
  ff_dim: 1024
  num_heads: 8
  num_layers: 4
  dropout: 0.1
  max_seq_len: 250
  attention: torch

#resume_run: europarl

train_config:
  artifacts_dir: /content/drive/MyDrive/nmt_lab/artifacts
  dataset: europarl_de-en_train (8)
  #validation_dataset: iwslt2017_iwslt2017-de-en_validation  # optional
  run_name: europarl
  seed: 42
  lr: 0.0003
  epochs: 10
  log_every: 100
  translate_every: 5000
  translate_examples:
    - Wir brauchen einen klaren Plan für den nächsten Schritt.
    - Der Ausschuss hat den Vorschlag gestern gebilligt.
    - Dieses Abkommen wird die Zusammenarbeit zwischen unseren Ländern stärken.
    - Das Morgenlicht fiel sanft über die Blumenwiese.
    - Sie lächelte, als die ersten Noten des Liedes den Raum füllten.
  spike_window: 100
  spike_factor: 3.0

data_loader_config:
  batch_size: 128
  shuffle: true
  num_workers: 4
  persistent_workers: true
  prefetch_factor: 4
  pin_memory: true